use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Internal metric ID (generated by Sequins, not from OTLP)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MetricId(Uuid);

impl MetricId {
    /// Generate a new random metric ID
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    /// Generate a deterministic metric ID from name and service name.
    ///
    /// **Legacy** — used by cold-tier query lookups and health checks where only
    /// the metric name and service name are available. Prefer `from_fields` for
    /// new ingest-path code.
    pub fn from_name_and_service(name: &str, service_name: &str) -> Self {
        let namespace = Uuid::NAMESPACE_DNS;
        let combined = format!("{}\0{}", name, service_name);
        let uuid = Uuid::new_v5(&namespace, combined.as_bytes());
        Self(uuid)
    }

    /// Generate a deterministic metric ID from the full set of identity fields.
    ///
    /// Two metrics are considered the same if they share the same name, description,
    /// unit, metric_type, resource_id, and scope_id. Null bytes are used as field
    /// separators to prevent ambiguity across different field combinations.
    pub fn from_fields(
        name: &str,
        description: &str,
        unit: &str,
        metric_type: &str,
        resource_id: u32,
        scope_id: u32,
    ) -> Self {
        let namespace = Uuid::NAMESPACE_DNS;
        let combined = format!(
            "{}\0{}\0{}\0{}\0{}\0{}",
            name, description, unit, metric_type, resource_id, scope_id
        );
        let uuid = Uuid::new_v5(&namespace, combined.as_bytes());
        Self(uuid)
    }

    /// Create from existing UUID
    pub fn from_uuid(uuid: Uuid) -> Self {
        Self(uuid)
    }

    /// Get inner UUID
    pub fn as_uuid(&self) -> Uuid {
        self.0
    }

    /// Convert to hex string (without hyphens)
    pub fn to_hex(&self) -> String {
        self.0.simple().to_string()
    }

    /// Parse from hex string
    ///
    /// # Errors
    ///
    /// Returns an error if the string is not a valid UUID
    pub fn from_hex(s: &str) -> Result<Self, String> {
        Uuid::parse_str(s)
            .map(Self::from_uuid)
            .map_err(|e| format!("Invalid UUID: {}", e))
    }
}

impl Default for MetricId {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_metric_id_generation() {
        let id1 = MetricId::new();
        let id2 = MetricId::new();
        assert_ne!(id1, id2);
    }

    #[test]
    fn test_metric_id_roundtrip() {
        let uuid = Uuid::new_v4();
        let id = MetricId::from_uuid(uuid);
        assert_eq!(id.as_uuid(), uuid);
    }

    #[test]
    fn test_from_fields_deterministic() {
        let a = MetricId::from_fields("req.duration", "desc", "s", "histogram", 1, 2);
        let b = MetricId::from_fields("req.duration", "desc", "s", "histogram", 1, 2);
        assert_eq!(a, b);
    }

    #[test]
    fn test_from_fields_differs_by_resource() {
        let a = MetricId::from_fields("req.duration", "", "s", "gauge", 1, 0);
        let b = MetricId::from_fields("req.duration", "", "s", "gauge", 2, 0);
        assert_ne!(a, b);
    }

    #[test]
    fn test_from_fields_differs_by_type() {
        let a = MetricId::from_fields("req.count", "", "", "counter", 1, 0);
        let b = MetricId::from_fields("req.count", "", "", "gauge", 1, 0);
        assert_ne!(a, b);
    }
}
