use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Internal profile ID (generated by Sequins, not from OTLP)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ProfileId(Uuid);

impl ProfileId {
    /// Generate a new random profile ID
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    /// Create from existing UUID
    pub fn from_uuid(uuid: Uuid) -> Self {
        Self(uuid)
    }

    /// Get inner UUID
    pub fn as_uuid(&self) -> Uuid {
        self.0
    }

    /// Convert to hex string (without hyphens)
    pub fn to_hex(&self) -> String {
        self.0.simple().to_string()
    }

    /// Parse from hex string
    ///
    /// # Errors
    ///
    /// Returns an error if the string is not a valid UUID
    pub fn from_hex(s: &str) -> Result<Self, String> {
        Uuid::parse_str(s)
            .map(Self::from_uuid)
            .map_err(|e| format!("Invalid UUID: {}", e))
    }
}

impl Default for ProfileId {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_profile_id_generation() {
        let id1 = ProfileId::new();
        let id2 = ProfileId::new();

        assert_ne!(id1, id2);
    }

    #[test]
    fn test_profile_id_roundtrip() {
        let uuid = Uuid::new_v4();
        let id = ProfileId::from_uuid(uuid);
        assert_eq!(id.as_uuid(), uuid);
    }
}
