apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sequins.fullname" . }}
  labels:
    {{- include "sequins.labels" . | nindent 4 }}
data:
  # Data retention policies
  retention.traces: {{ .Values.storage.retention.traces | quote }}
  retention.logs: {{ .Values.storage.retention.logs | quote }}
  retention.metrics: {{ .Values.storage.retention.metrics | quote }}
  retention.profiles: {{ .Values.storage.retention.profiles | quote }}
