{{- if not .Values.storage.s3.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sequins.fullname" . }}-s3
  labels:
    {{- include "sequins.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.storage.s3.accessKeyId }}
  {{ .Values.storage.s3.accessKeyIdKey }}: {{ .Values.storage.s3.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.storage.s3.secretAccessKey }}
  {{ .Values.storage.s3.secretAccessKeyKey }}: {{ .Values.storage.s3.secretAccessKey | b64enc | quote }}
  {{- end }}
{{- end }}
