apiVersion: v1
kind: Service
metadata:
  name: {{ include "sequins.fullname" . }}-otlp
  labels:
    {{- include "sequins.labels" . | nindent 4 }}
    app.kubernetes.io/component: otlp
  {{- with .Values.otlp.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.otlp.service.type }}
  ports:
  - port: {{ .Values.otlp.service.grpcPort }}
    targetPort: otlp-grpc
    protocol: TCP
    name: otlp-grpc
  - port: {{ .Values.otlp.service.httpPort }}
    targetPort: otlp-http
    protocol: TCP
    name: otlp-http
  selector:
    {{- include "sequins.selectorLabels" . | nindent 4 }}
