// This file is @generated by prost-build.
/// SeqlExtension is embedded in Substrait Plan.advanced_extensions.enhancement
/// as a protobuf Any, allowing any Flight SQL client to send a Substrait plan
/// and receive Arrow IPC streams with full SeQL semantics.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SeqlExtension {
    /// UI rendering hint (table, timeseries, heatmap, etc.)
    #[prost(string, tag = "1")]
    pub response_shape: ::prost::alloc::string::String,
    /// Primary signal type (spans, logs, datapoints, etc.)
    #[prost(string, tag = "2")]
    pub signal: ::prost::alloc::string::String,
    /// Time range for the query
    #[prost(message, optional, tag = "3")]
    pub time_range: ::core::option::Option<TimeRange>,
    /// Query execution mode
    #[prost(enumeration = "QueryMode", tag = "4")]
    pub mode: i32,
    /// Optional cursor for live query continuation (WAL sequence number)
    #[prost(uint64, optional, tag = "5")]
    pub cursor: ::core::option::Option<u64>,
    /// Aliases for auxiliary plan roots (relations\[1\], \[2\], etc.)
    /// auxiliary_aliases\[i\] corresponds to plan.relations\[i+1\]
    #[prost(string, repeated, tag = "6")]
    pub auxiliary_aliases: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Signal names for auxiliary plan roots (relations\[1\], \[2\], etc.)
    /// auxiliary_signals\[i\] is the signal type for plan.relations\[i+1\]
    /// Used by the server to route live WAL broadcasts to the right table.
    #[prost(string, repeated, tag = "7")]
    pub auxiliary_signals: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Complete serialized Substrait Plan bytes for each auxiliary merge root.
    /// Each entry is a self-contained Plan (with its own extensions).
    #[prost(bytes = "vec", repeated, tag = "8")]
    pub auxiliary_plan_bytes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// Time range specification
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TimeRange {
    #[prost(oneof = "time_range::Range", tags = "1, 2")]
    pub range: ::core::option::Option<time_range::Range>,
}
/// Nested message and enum types in `TimeRange`.
pub mod time_range {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Range {
        /// Sliding window: look back this many nanoseconds from now
        #[prost(uint64, tag = "1")]
        SlidingWindowNs(u64),
        /// Absolute range with explicit start/end
        #[prost(message, tag = "2")]
        Absolute(super::AbsoluteRange),
    }
}
/// Absolute time range with explicit start and end
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AbsoluteRange {
    #[prost(uint64, tag = "1")]
    pub start_ns: u64,
    #[prost(uint64, tag = "2")]
    pub end_ns: u64,
}
/// Query execution mode
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum QueryMode {
    Snapshot = 0,
    Live = 1,
}
impl QueryMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Snapshot => "SNAPSHOT",
            Self::Live => "LIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SNAPSHOT" => Some(Self::Snapshot),
            "LIVE" => Some(Self::Live),
            _ => None,
        }
    }
}
