#ifndef SEQUINS_FFI_H
#define SEQUINS_FFI_H

#pragma once

/* Warning: this file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
/* Opaque type for std::ffi::CString */
typedef struct CString CString;


/**
 * Tag for discriminated union CAttributeValue
 */
typedef enum CAttributeValueTag {
  String = 0,
  Bool = 1,
  Int = 2,
  Double = 3,
  StringArray = 4,
  BoolArray = 5,
  IntArray = 6,
  DoubleArray = 7,
} CAttributeValueTag;

/**
 * C-compatible delta operation type
 */
typedef enum CDeltaOpType {
  /**
   * New rows were added (data is Arrow IPC streaming-format bytes)
   */
  Append = 0,
  /**
   * An existing row was updated
   */
  Update = 1,
  /**
   * A row left the time window
   */
  Expire = 2,
  /**
   * All rows replaced with new result set
   */
  Replace = 3,
} CDeltaOpType;

/**
 * C-compatible grouping pattern enum
 */
typedef enum CGroupingPattern {
  StatisticalVariants = 0,
  HistogramFamily = 1,
  AttributeStreams = 2,
  Custom = 3,
  Namespace = 4,
} CGroupingPattern;

/**
 * C-compatible log severity
 */
typedef enum CLogSeverity {
  LogTrace = 1,
  LogDebug = 5,
  LogInfo = 9,
  LogWarn = 13,
  LogError = 17,
  LogFatal = 21,
} CLogSeverity;

/**
 * C-compatible metric type
 */
typedef enum CMetricType {
  Gauge = 0,
  Counter = 1,
  Histogram = 2,
  Summary = 3,
} CMetricType;

/**
 * C-compatible profile type
 */
typedef enum CProfileType {
  Cpu = 0,
  Memory = 1,
  Goroutine = 2,
  Other = 3,
} CProfileType;

/**
 * C-compatible response shape tag
 */
typedef enum CResponseShape {
  /**
   * Flat table
   */
  Table = 0,
  /**
   * Time-series lines
   */
  TimeSeries = 1,
  /**
   * 2-D heatmap
   */
  Heatmap = 2,
  /**
   * Hierarchical span tree
   */
  TraceTree = 3,
  /**
   * Waterfall trace timeline
   */
  TraceTimeline = 4,
  /**
   * Log pattern groups
   */
  PatternGroups = 5,
  /**
   * Single scalar value
   */
  Scalar = 6,
} CResponseShape;

/**
 * C-compatible span kind
 */
typedef enum CSpanKind {
  Unspecified = 0,
  Internal = 1,
  Server = 2,
  Client = 3,
  Producer = 4,
  Consumer = 5,
} CSpanKind;

/**
 * C-compatible span status
 */
typedef enum CSpanStatus {
  Unset = 0,
  Ok = 1,
  Error = 2,
} CSpanStatus;

/**
 * Discriminant for [`CViewDelta`].
 *
 * Variants are prefixed with `ViewDelta` to avoid collisions with other C
 * enums in the same global namespace (e.g. `CSpanStatus::Error`).
 */
enum CViewDeltaType {
  /**
   * New rows appended to a table (`data` carries Arrow IPC).
   */
  ViewDeltaRowsAppended = 0,
  /**
   * Rows expired from the live time window (`count` is the number expired).
   */
  ViewDeltaRowsExpired = 1,
  /**
   * Entire table replaced (`data` carries Arrow IPC).
   */
  ViewDeltaTableReplaced = 2,
  /**
   * New entity created (`descriptor` + `data` carry Arrow IPC).
   */
  ViewDeltaEntityCreated = 3,
  /**
   * Entity's mutable data changed (`data` carries Arrow IPC).
   */
  ViewDeltaEntityDataReplaced = 4,
  /**
   * Entity removed.
   */
  ViewDeltaEntityRemoved = 5,
  /**
   * Initial data load complete; live updates are now streaming.
   */
  ViewDeltaReady = 6,
  /**
   * Periodic keepalive (`watermark_ns` is set).
   */
  ViewDeltaHeartbeat = 7,
  /**
   * Non-fatal warning (`message` is set).
   */
  ViewDeltaWarning = 8,
  /**
   * Fatal error (`message` is set).
   */
  ViewDeltaError = 9,
};
typedef uint32_t CViewDeltaType;

/**
 * C-compatible visualization type enum
 */
typedef enum CVisualizationType {
  VisualizationMultiLineChart = 0,
  VisualizationBoxPlot = 1,
  VisualizationHistogram = 2,
  VisualizationRangeChart = 3,
  VisualizationStackedArea = 4,
  VisualizationSeparateCharts = 5,
} CVisualizationType;

/**
 * Opaque C type for DataSource - never actually defined
 * This provides type safety without exposing internals
 */
typedef struct CDataSource CDataSource;

/**
 * Opaque parse result returned by `sequins_seql_parse`
 */
typedef struct CParseResult CParseResult;

/**
 * An opaque handle to a running SeQL stream
 */
typedef struct CStreamHandle CStreamHandle;

/**
 * Opaque handle to a running reactive view.
 */
typedef struct CViewHandle CViewHandle;

/**
 * OTLP server configuration for local mode
 */
typedef struct COtlpServerConfig {
  /**
   * gRPC port (0 = disabled, default 4317)
   */
  uint16_t grpc_port;
  /**
   * HTTP port (0 = disabled, default 4318)
   */
  uint16_t http_port;
} COtlpServerConfig;

/**
 * C-compatible retention policy configuration
 */
typedef struct CRetentionPolicy {
  /**
   * How long to keep span data (seconds)
   */
  int64_t spans_retention_secs;
  /**
   * How long to keep log data (seconds)
   */
  int64_t logs_retention_secs;
  /**
   * How long to keep metric data (seconds)
   */
  int64_t metrics_retention_secs;
  /**
   * How long to keep profile data (seconds)
   */
  int64_t profiles_retention_secs;
} CRetentionPolicy;

/**
 * C-compatible storage statistics
 */
typedef struct CStorageStats {
  /**
   * Number of spans in storage
   */
  uintptr_t span_count;
  /**
   * Number of logs in storage
   */
  uintptr_t log_count;
  /**
   * Number of metrics in storage
   */
  uintptr_t metric_count;
  /**
   * Number of profiles in storage
   */
  uintptr_t profile_count;
} CStorageStats;

/**
 * C-compatible maintenance statistics
 */
typedef struct CMaintenanceStats {
  /**
   * Number of entries evicted from hot tier
   */
  uintptr_t entries_evicted;
  /**
   * Number of batches flushed to cold tier
   */
  uintptr_t batches_flushed;
} CMaintenanceStats;

/**
 * C-compatible health metric rule
 */
typedef struct CHealthMetricRule {
  /**
   * Metric name (e.g., "sequins.health.span_error_rate")
   */
  char *metric_name;
  /**
   * Service name filter (null = applies to all services)
   */
  char *service_name;
  /**
   * Warning threshold
   */
  double warning_threshold;
  /**
   * Error threshold
   */
  double error_threshold;
  /**
   * Whether higher values are worse (true) or lower values are worse (false)
   */
  bool higher_is_worse;
  /**
   * Weight for overall health score (0.0-1.0)
   */
  double weight;
  /**
   * Human-readable display name
   */
  char *display_name;
} CHealthMetricRule;

/**
 * C-compatible array of health metric rules
 */
typedef struct CHealthMetricRuleArray {
  struct CHealthMetricRule *data;
  uintptr_t len;
} CHealthMetricRuleArray;

/**
 * C-compatible health threshold configuration
 */
typedef struct CHealthThresholdConfig {
  struct CHealthMetricRuleArray rules;
} CHealthThresholdConfig;

/**
 * C-compatible schema frame — describes the shape and columns
 */
typedef struct CSchemaFrame {
  /**
   * Result shape
   */
  enum CResponseShape shape;
  /**
   * Number of columns
   */
  unsigned int column_count;
  /**
   * Column names (null-terminated strings)
   */
  char **column_names;
  /**
   * Watermark at query start (nanoseconds since epoch)
   */
  uint64_t initial_watermark_ns;
  /**
   * Table name for multi-table responses (null = primary table, non-null = auxiliary table alias)
   */
  char *table;
} CSchemaFrame;

/**
 * C-compatible data frame — a batch of Arrow IPC bytes
 */
typedef struct CDataFrame {
  /**
   * Number of rows
   */
  unsigned int row_count;
  /**
   * Arrow IPC streaming-format bytes
   */
  uint8_t *ipc_data;
  /**
   * Length of `ipc_data` in bytes
   */
  uintptr_t ipc_len;
  /**
   * Table name for multi-table responses (null = primary table, non-null = auxiliary table alias)
   */
  char *table;
} CDataFrame;

/**
 * C-compatible delta operation
 */
typedef struct CDeltaOp {
  /**
   * Operation type
   */
  enum CDeltaOpType op_type;
  /**
   * Row ID: start_row_id for Append/Replace, row_id for Update/Expire
   */
  uint64_t row_id;
  /**
   * Payload bytes:
   *   Append/Replace: Arrow IPC streaming-format bytes
   *   Update: JSON bytes (UTF-8, array of `[col_idx, value]` pairs)
   *   Expire: NULL
   */
  uint8_t *data;
  /**
   * Length of `data` in bytes (0 for Expire)
   */
  uintptr_t data_len;
} CDeltaOp;

/**
 * C-compatible delta frame — incremental updates for live queries
 */
typedef struct CDeltaFrame {
  /**
   * New query watermark (nanoseconds since epoch)
   */
  uint64_t watermark_ns;
  /**
   * Number of operations
   */
  unsigned int ops_count;
  /**
   * Array of delta operations
   */
  struct CDeltaOp *ops;
} CDeltaFrame;

/**
 * C-compatible heartbeat frame — keepalive for live queries
 */
typedef struct CHeartbeatFrame {
  /**
   * Current watermark (nanoseconds since epoch)
   */
  uint64_t watermark_ns;
} CHeartbeatFrame;

/**
 * C-compatible complete frame — query finished
 */
typedef struct CCompleteFrame {
  /**
   * Wall-clock time in microseconds
   */
  uint64_t execution_time_us;
  /**
   * Rows scanned before filtering
   */
  uint64_t rows_scanned;
  /**
   * Bytes read from storage
   */
  uint64_t bytes_read;
  /**
   * Rows in the final result
   */
  uint64_t rows_returned;
  /**
   * Number of warnings emitted
   */
  unsigned int warning_count;
} CCompleteFrame;

/**
 * C-compatible warning frame
 */
typedef struct CWarningFrame {
  /**
   * Warning code
   */
  unsigned int code;
  /**
   * Human-readable message (null-terminated, caller must free)
   */
  char *message;
} CWarningFrame;

/**
 * C-compatible query error
 */
typedef struct CQueryError {
  /**
   * Error code (0=UnknownField, 1=InvalidAst, 2=UnsupportedStage, 3=ResourceLimit, 4=Execution)
   */
  unsigned int code;
  /**
   * Human-readable message (null-terminated, caller must free)
   */
  char *message;
} CQueryError;

/**
 * C vtable for receiving SeQL frame callbacks
 *
 * All callbacks may be invoked from a Tokio worker thread.
 * Implementations must be thread-safe and return quickly.
 */
typedef struct CFrameSinkVTable {
  /**
   * Called once with the result schema (before any data frames)
   */
  void (*on_schema)(const struct CSchemaFrame*, void *ctx);
  /**
   * Called with each batch of rows
   */
  void (*on_data)(const struct CDataFrame*, void *ctx);
  /**
   * Called with incremental updates (live queries only)
   */
  void (*on_delta)(const struct CDeltaFrame*, void *ctx);
  /**
   * Called periodically as keepalive (live queries only)
   */
  void (*on_heartbeat)(const struct CHeartbeatFrame*, void *ctx);
  /**
   * Called when the query completes successfully
   */
  void (*on_complete)(const struct CCompleteFrame*, void *ctx);
  /**
   * Called for non-fatal warnings
   */
  void (*on_warning)(const struct CWarningFrame*, void *ctx);
  /**
   * Called if the query terminates with an error
   */
  void (*on_error)(const struct CQueryError*, void *ctx);
} CFrameSinkVTable;

/**
 * A single reactive update delivered to the frontend.
 *
 * Fields that are not applicable to a given `delta_type` are null/zero.
 *
 * ## Memory ownership
 * All heap-allocated fields (`table`, `key`, `data`, `descriptor`, `message`)
 * are owned by the `CViewDelta`. Free the entire batch with
 * `c_view_delta_batch_free` when done.
 */
typedef struct CViewDelta {
  /**
   * Delta variant tag.
   */
  CViewDeltaType delta_type;
  /**
   * Table identifier. `NULL` = primary table; non-NULL = auxiliary alias.
   * Applies to: RowsAppended, RowsExpired, TableReplaced.
   */
  char *table;
  /**
   * Entity key (e.g. path_key for flamegraph, metric_id for metrics).
   * Applies to: EntityCreated, EntityDataReplaced, EntityRemoved.
   */
  char *key;
  /**
   * Arrow IPC bytes for the payload (nullable).
   * - RowsAppended / TableReplaced: the row batch
   * - EntityCreated: the mutable data batch
   * - EntityDataReplaced: the updated mutable data batch
   */
  uint8_t *data;
  /**
   * Length of `data` in bytes.
   */
  uintptr_t data_len;
  /**
   * Arrow IPC bytes for the immutable descriptor (EntityCreated only).
   */
  uint8_t *descriptor;
  /**
   * Length of `descriptor` in bytes.
   */
  uintptr_t descriptor_len;
  /**
   * Number of rows expired (RowsExpired only).
   */
  uint64_t count;
  /**
   * Current watermark in nanoseconds since epoch (Heartbeat only).
   */
  uint64_t watermark_ns;
  /**
   * Warning/Error code (Warning only, 0 otherwise).
   */
  uint32_t code;
  /**
   * Human-readable message (Warning / Error only, NULL otherwise).
   */
  char *message;
} CViewDelta;

/**
 * C-compatible array of strings
 */
typedef struct CStringArray {
  char **data;
  uintptr_t len;
} CStringArray;

/**
 * C-compatible array of booleans
 */
typedef struct CBoolArray {
  bool *data;
  uintptr_t len;
} CBoolArray;

/**
 * C-compatible array of int64
 */
typedef struct CIntArray {
  int64_t *data;
  uintptr_t len;
} CIntArray;

/**
 * C-compatible array of doubles
 */
typedef struct CDoubleArray {
  double *data;
  uintptr_t len;
} CDoubleArray;

/**
 * Union for attribute value data
 */
typedef union CAttributeValueUnion {
  char *string_val;
  bool bool_val;
  int64_t int_val;
  double double_val;
  struct CStringArray string_array;
  struct CBoolArray bool_array;
  struct CIntArray int_array;
  struct CDoubleArray double_array;
} CAttributeValueUnion;

/**
 * C-compatible attribute value (discriminated union)
 */
typedef struct CAttributeValue {
  enum CAttributeValueTag tag;
  union CAttributeValueUnion value;
} CAttributeValue;

/**
 * C-compatible key-value pair
 */
typedef struct CKeyValue {
  char *key;
  struct CAttributeValue value;
} CKeyValue;

/**
 * C-compatible array of key-value pairs (for OTEL attributes)
 */
typedef struct CKeyValueArray {
  struct CKeyValue *data;
  uintptr_t len;
} CKeyValueArray;

/**
 * C-compatible timestamp (nanoseconds since epoch)
 */
typedef int64_t CTimestamp;

/**
 * C-compatible query cursor for two-phase query pattern
 *
 * The cursor contains an opaque string that encodes the timestamp when the
 * historical query was executed. It should be passed to subscribe functions
 * to resume from where the query left off.
 */
typedef struct CQueryCursor {
  /**
   * Opaque cursor string (base64-encoded, must be freed with sequins_string_free)
   */
  char *opaque;
  /**
   * Timestamp in nanoseconds (for inspection, but use opaque for subscribe)
   */
  CTimestamp timestamp_nanos;
} CQueryCursor;

/**
 * C-compatible log entry
 */
typedef struct CLogEntry {
  /**
   * Log ID (UUID string, must be freed)
   */
  char *id;
  /**
   * Timestamp (nanoseconds since epoch)
   */
  CTimestamp timestamp;
  /**
   * Observed timestamp (nanoseconds since epoch)
   */
  CTimestamp observed_timestamp;
  /**
   * Service name (must be freed)
   */
  char *service_name;
  /**
   * Severity level
   */
  enum CLogSeverity severity;
  /**
   * Log message body (must be freed)
   */
  char *body;
  /**
   * Log attributes
   */
  struct CKeyValueArray attributes;
  /**
   * Trace ID (32-char hex string, must be freed), null if not linked to trace
   */
  char *trace_id;
  /**
   * Span ID (16-char hex string, must be freed), null if not linked to span
   */
  char *span_id;
} CLogEntry;

/**
 * C-compatible array of logs
 */
typedef struct CLogEntryArray {
  /**
   * Pointer to array of logs
   */
  struct CLogEntry *data;
  /**
   * Number of logs in the array
   */
  uintptr_t len;
} CLogEntryArray;

/**
 * C-compatible log query result (historical data + cursor)
 */
typedef struct CLogQueryResult {
  /**
   * Array of historical logs
   */
  struct CLogEntryArray logs;
  /**
   * Cursor for subscribing to live updates
   */
  struct CQueryCursor cursor;
} CLogQueryResult;

/**
 * C-compatible log query parameters
 */
typedef struct CLogQuery {
  /**
   * Service name filter (null-terminated string), null if not filtering
   */
  const char *service;
  /**
   * Time range start (nanoseconds since epoch)
   */
  CTimestamp start_time;
  /**
   * Time range end (nanoseconds since epoch)
   */
  CTimestamp end_time;
  /**
   * Array of severity levels to include (null = all severities)
   */
  const enum CLogSeverity *severities;
  /**
   * Number of severity levels in the array
   */
  uintptr_t severities_len;
  /**
   * Full-text search in log body (null-terminated string), null if not searching
   */
  const char *search;
  /**
   * Limit number of results, 0 = no limit
   */
  uintptr_t limit;
} CLogQuery;

/**
 * C-compatible metric data point
 */
typedef struct CMetricDataPoint {
  /**
   * Metric ID this point belongs to (UUID hex string, must be freed)
   */
  char *metric_id;
  /**
   * Timestamp (nanoseconds since epoch)
   */
  CTimestamp timestamp;
  /**
   * Numeric value
   */
  double value;
  /**
   * Attribute keys (must be freed)
   */
  struct CStringArray attribute_keys;
  /**
   * Attribute values (must be freed)
   */
  struct CStringArray attribute_values;
} CMetricDataPoint;

/**
 * C-compatible array of metric data points
 */
typedef struct CMetricDataPointArray {
  /**
   * Pointer to array of data points
   */
  struct CMetricDataPoint *data;
  /**
   * Number of data points in the array
   */
  uintptr_t len;
} CMetricDataPointArray;

/**
 * C-compatible metric data point query result (historical data + cursor)
 */
typedef struct CMetricDataPointQueryResult {
  /**
   * Array of historical data points
   */
  struct CMetricDataPointArray data_points;
  /**
   * Cursor for subscribing to live updates
   */
  struct CQueryCursor cursor;
} CMetricDataPointQueryResult;

/**
 * C-compatible metric data point query parameters
 */
typedef struct CMetricDataPointQuery {
  /**
   * Metric ID to fetch data points for (UUID hex string)
   */
  const char *metric_id;
  /**
   * Time range start (nanoseconds since epoch)
   */
  CTimestamp start_time;
  /**
   * Time range end (nanoseconds since epoch)
   */
  CTimestamp end_time;
  /**
   * Bucket duration for downsampling (nanoseconds), 0 = no downsampling
   */
  int64_t bucket_duration_nanos;
} CMetricDataPointQuery;

/**
 * C-compatible metric definition
 */
typedef struct CMetric {
  /**
   * Metric ID (UUID hex string, must be freed)
   */
  char *id;
  /**
   * Metric name (must be freed)
   */
  char *name;
  /**
   * Description (must be freed)
   */
  char *description;
  /**
   * Unit of measurement (must be freed)
   */
  char *unit;
  /**
   * Metric type
   */
  enum CMetricType metric_type;
  /**
   * Service name (must be freed)
   */
  char *service_name;
  /**
   * Whether this metric was generated internally (e.g., health metrics)
   */
  bool is_generated;
} CMetric;

/**
 * C-compatible array of metrics
 */
typedef struct CMetricArray {
  /**
   * Pointer to array of metrics
   */
  struct CMetric *data;
  /**
   * Number of metrics in the array
   */
  uintptr_t len;
} CMetricArray;

/**
 * C-compatible metric query result (historical data + cursor)
 */
typedef struct CMetricQueryResult {
  /**
   * Array of historical metrics
   */
  struct CMetricArray metrics;
  /**
   * Cursor for subscribing to live updates
   */
  struct CQueryCursor cursor;
} CMetricQueryResult;

/**
 * C-compatible metric query parameters
 */
typedef struct CMetricQuery {
  /**
   * Metric name filter (null-terminated string), null if not filtering
   */
  const char *name;
  /**
   * Service name filter (null-terminated string), null if not filtering
   */
  const char *service;
  /**
   * Time range start (nanoseconds since epoch)
   */
  CTimestamp start_time;
  /**
   * Time range end (nanoseconds since epoch)
   */
  CTimestamp end_time;
  /**
   * Limit number of results, 0 = no limit
   */
  uintptr_t limit;
} CMetricQuery;

/**
 * C-compatible metric group
 */
typedef struct CMetricGroup {
  /**
   * Base name of the metric group (e.g., "nodejs.eventloop.delay")
   */
  char *base_name;
  /**
   * Names of all metrics in this group
   */
  struct CStringArray metric_names;
  /**
   * The detected grouping pattern
   */
  enum CGroupingPattern pattern;
  /**
   * Service name this group belongs to
   */
  char *service_name;
  /**
   * Metric type (if all metrics share the same type)
   */
  enum CMetricType metric_type;
  /**
   * Whether metric_type is valid
   */
  bool has_metric_type;
  /**
   * Shared unit for all metrics in the group
   */
  char *unit;
  /**
   * Recommended visualization type for this group
   */
  enum CVisualizationType visualization;
} CMetricGroup;

/**
 * C-compatible array of metric groups
 */
typedef struct CMetricGroupArray {
  /**
   * Pointer to array of metric groups
   */
  struct CMetricGroup *data;
  /**
   * Number of groups in the array
   */
  uintptr_t len;
} CMetricGroupArray;

/**
 * C-compatible stack frame (single function in a call stack)
 */
typedef struct CStackFrame {
  /**
   * Function name (must be freed)
   */
  char *function_name;
  /**
   * Source file path (null if unknown, must be freed)
   */
  char *file;
  /**
   * Source line number (0 if unknown)
   */
  uint32_t line;
  /**
   * Module or package name (null if unknown, must be freed)
   */
  char *module;
} CStackFrame;

/**
 * C-compatible array of stack frames
 */
typedef struct CStackFrameArray {
  struct CStackFrame *data;
  uintptr_t len;
} CStackFrameArray;

/**
 * C-compatible profile sample with resolved stack frames
 */
typedef struct CProfileSample {
  /**
   * Profile ID (hex string, must be freed)
   */
  char *profile_id;
  /**
   * Timestamp (nanoseconds since epoch)
   */
  CTimestamp timestamp;
  /**
   * Service name (must be freed)
   */
  char *service_name;
  /**
   * Profile type
   */
  enum CProfileType profile_type;
  /**
   * Value type label (e.g., "cpu", "alloc_objects", must be freed)
   */
  char *value_type;
  /**
   * Sample value (unit depends on value_type)
   */
  int64_t value;
  /**
   * Call stack — leaf (innermost) to root (outermost)
   */
  struct CStackFrameArray stack;
  /**
   * Associated trace ID (32-char hex string, null if not linked, must be freed)
   */
  char *trace_id;
} CProfileSample;

/**
 * C-compatible array of profile samples
 */
typedef struct CProfileSampleArray {
  struct CProfileSample *data;
  uintptr_t len;
} CProfileSampleArray;

/**
 * C-compatible profile sample query result (historical data + cursor)
 */
typedef struct CProfileSampleQueryResult {
  struct CProfileSampleArray samples;
  struct CQueryCursor cursor;
} CProfileSampleQueryResult;

/**
 * C-compatible profile sample query parameters
 */
typedef struct CProfileSampleQuery {
  /**
   * Service name filter (null-terminated string), null if not filtering
   */
  const char *service;
  /**
   * Profile type filter (null-terminated string), null if not filtering
   */
  const char *profile_type;
  /**
   * Value type filter (null-terminated string), null if not filtering
   */
  const char *value_type;
  /**
   * Time range start (nanoseconds since epoch)
   */
  CTimestamp start_time;
  /**
   * Time range end (nanoseconds since epoch)
   */
  CTimestamp end_time;
  /**
   * Trace ID filter (32-char hex string), null if not filtering
   */
  const char *trace_id;
  /**
   * Limit number of results, 0 = no limit
   */
  uintptr_t limit;
} CProfileSampleQuery;

/**
 * C-compatible byte array (for pprof data)
 */
typedef struct CByteArray {
  uint8_t *data;
  uintptr_t len;
} CByteArray;

/**
 * C-compatible profile
 */
typedef struct CProfile {
  /**
   * Profile ID (UUID hex string, must be freed)
   */
  char *id;
  /**
   * Timestamp (nanoseconds since epoch)
   */
  CTimestamp timestamp;
  /**
   * Service name (must be freed)
   */
  char *service_name;
  /**
   * Profile type
   */
  enum CProfileType profile_type;
  /**
   * Sample type (e.g., "cpu", "alloc_objects", must be freed)
   */
  char *sample_type;
  /**
   * Sample unit (e.g., "nanoseconds", "bytes", must be freed)
   */
  char *sample_unit;
  /**
   * Encoded pprof data (must be freed with sequins_byte_array_free)
   */
  struct CByteArray data;
  /**
   * Associated trace ID (32-char hex string, null if not linked, must be freed)
   */
  char *trace_id;
} CProfile;

/**
 * C-compatible array of profiles
 */
typedef struct CProfileArray {
  /**
   * Pointer to array of profiles
   */
  struct CProfile *data;
  /**
   * Number of profiles in the array
   */
  uintptr_t len;
} CProfileArray;

/**
 * C-compatible profile query result (historical data + cursor)
 */
typedef struct CProfileQueryResult {
  /**
   * Array of historical profiles
   */
  struct CProfileArray profiles;
  /**
   * Cursor for subscribing to live updates
   */
  struct CQueryCursor cursor;
} CProfileQueryResult;

/**
 * C-compatible profile query parameters
 */
typedef struct CProfileQuery {
  /**
   * Service name filter (null-terminated string), null if not filtering
   */
  const char *service;
  /**
   * Profile type filter (null-terminated string), null if not filtering
   */
  const char *profile_type;
  /**
   * Time range start (nanoseconds since epoch)
   */
  CTimestamp start_time;
  /**
   * Time range end (nanoseconds since epoch)
   */
  CTimestamp end_time;
  /**
   * Trace ID filter (32-char hex string), null if not filtering
   */
  const char *trace_id;
  /**
   * Limit number of results, 0 = no limit
   */
  uintptr_t limit;
} CProfileQuery;

/**
 * C-compatible resource attribute (key with comma-separated values)
 */
typedef struct CResourceAttribute {
  /**
   * Attribute key (e.g., "service.version")
   */
  char *key;
  /**
   * Comma-separated values (e.g., "1.0.0, 1.0.1")
   */
  char *values;
} CResourceAttribute;

/**
 * C-compatible array of resource attributes
 */
typedef struct CResourceAttributeArray {
  struct CResourceAttribute *data;
  uintptr_t len;
} CResourceAttributeArray;

/**
 * C-compatible service entry
 */
typedef struct CService {
  /**
   * Service name (must be freed)
   */
  char *name;
  /**
   * Number of spans from this service
   */
  uintptr_t span_count;
  /**
   * Number of logs from this service
   */
  uintptr_t log_count;
  /**
   * Aggregated resource attributes
   */
  struct CResourceAttributeArray resource_attributes;
} CService;

/**
 * C-compatible array of services
 */
typedef struct CServiceArray {
  struct CService *data;
  uintptr_t len;
} CServiceArray;

/**
 * C-compatible span event
 */
typedef struct CSpanEvent {
  /**
   * Event timestamp (nanoseconds since epoch)
   */
  CTimestamp timestamp;
  /**
   * Event name (null-terminated string, must be freed)
   */
  char *name;
  /**
   * Event attributes
   */
  struct CKeyValueArray attributes;
} CSpanEvent;

/**
 * C-compatible array of span events
 */
typedef struct CSpanEventArray {
  struct CSpanEvent *data;
  uintptr_t len;
} CSpanEventArray;

/**
 * C-compatible span
 */
typedef struct CSpan {
  /**
   * Trace ID (32-char hex string, must be freed)
   */
  char *trace_id;
  /**
   * Span ID (16-char hex string, must be freed)
   */
  char *span_id;
  /**
   * Parent span ID (16-char hex string, must be freed), null if root span
   */
  char *parent_span_id;
  /**
   * Service name (must be freed)
   */
  char *service_name;
  /**
   * Operation name (must be freed)
   */
  char *operation_name;
  /**
   * Start time (nanoseconds since epoch)
   */
  CTimestamp start_time;
  /**
   * End time (nanoseconds since epoch)
   */
  CTimestamp end_time;
  /**
   * Duration (nanoseconds)
   */
  int64_t duration;
  /**
   * Span attributes
   */
  struct CKeyValueArray attributes;
  /**
   * Span events
   */
  struct CSpanEventArray events;
  /**
   * Span status
   */
  enum CSpanStatus status;
  /**
   * Span kind
   */
  enum CSpanKind span_kind;
} CSpan;

/**
 * C-compatible array of spans
 */
typedef struct CSpanArray {
  /**
   * Pointer to array of spans
   */
  struct CSpan *data;
  /**
   * Number of spans in the array
   */
  uintptr_t len;
} CSpanArray;

/**
 * C-compatible span query result (historical data + cursor)
 */
typedef struct CSpanQueryResult {
  /**
   * Array of historical spans
   */
  struct CSpanArray spans;
  /**
   * Cursor for subscribing to live updates
   */
  struct CQueryCursor cursor;
} CSpanQueryResult;

/**
 * C-compatible span query parameters
 */
typedef struct CSpanQuery {
  /**
   * Trace ID filter (32-char hex string), null if not filtering
   */
  const char *trace_id;
  /**
   * Service name filter (null-terminated string), null if not filtering
   */
  const char *service;
  /**
   * Time range start (nanoseconds since epoch)
   */
  CTimestamp start_time;
  /**
   * Time range end (nanoseconds since epoch)
   */
  CTimestamp end_time;
  /**
   * Limit number of results, 0 = no limit
   */
  uintptr_t limit;
} CSpanQuery;

/**
 * Create a new local data source with embedded storage
 *
 * # Arguments
 * * `db_path` - Path to SQLite database file
 * * `config` - OTLP server configuration (ports to bind)
 * * `error_out` - Output parameter for error message (if any)
 *
 * # Returns
 * * Pointer to CDataSource on success, null on failure
 * * On failure, `error_out` contains error message (caller must free with `sequins_string_free`)
 *
 * # Safety
 * * `db_path` must be a valid null-terminated C string
 * * Caller must call `sequins_data_source_free` when done
 */
struct CDataSource *sequins_data_source_new_local(const char *db_path,
                                                  struct COtlpServerConfig _config,
                                                  char **error_out);

/**
 * Create a new remote data source (connects to sequins-daemon)
 *
 * # Arguments
 * * `query_url` - URL for query API endpoint
 * * `management_url` - URL for management API endpoint
 * * `error_out` - Output parameter for error message (if any)
 *
 * # Returns
 * * Pointer to CDataSource on success, null on failure
 * * On failure, `error_out` contains error message (caller must free with `sequins_string_free`)
 *
 * # Safety
 * * `query_url` and `management_url` must be valid null-terminated C strings
 * * Caller must call `sequins_data_source_free` when done
 */
struct CDataSource *sequins_data_source_new_remote(const char *query_url,
                                                   const char *management_url,
                                                   char **error_out);

/**
 * Free a DataSource and all associated resources
 *
 * # Safety
 * * `data_source` must be a valid pointer returned from `sequins_data_source_new_*`
 * * Must only be called once per DataSource
 * * For local mode, OTLP server will be stopped if running
 */
void sequins_data_source_free(struct CDataSource *data_source);

/**
 * Start OTLP server for local data source
 *
 * # Arguments
 * * `data_source` - Local data source
 * * `config` - OTLP server configuration
 * * `error_out` - Output parameter for error message (if any)
 *
 * # Returns
 * * true on success, false on failure
 * * On failure, `error_out` contains error message
 *
 * # Safety
 * * `data_source` must be a valid local DataSource
 * * Only works with local DataSource (returns error for remote)
 */
bool sequins_data_source_start_otlp_server(struct CDataSource *data_source,
                                           struct COtlpServerConfig config,
                                           char **error_out);

/**
 * Stop OTLP server for local data source
 *
 * # Arguments
 * * `data_source` - Local data source
 *
 * # Safety
 * * `data_source` must be a valid local DataSource
 * * Idempotent - safe to call even if server not running
 */
void sequins_data_source_stop_otlp_server(struct CDataSource *data_source);

/**
 * Get OTLP server ports for local data source
 *
 * # Arguments
 * * `data_source` - Local data source
 * * `grpc_port_out` - Output parameter for gRPC port (0 if disabled)
 * * `http_port_out` - Output parameter for HTTP port (0 if disabled)
 *
 * # Returns
 * * true if server is running, false otherwise
 *
 * # Safety
 * * `data_source` must be a valid local DataSource
 * * `grpc_port_out` and `http_port_out` must be valid pointers
 */
bool sequins_data_source_get_otlp_ports(struct CDataSource *data_source,
                                        uint16_t *grpc_port_out,
                                        uint16_t *http_port_out);

/**
 * Free a string allocated by Rust
 *
 * # Safety
 * * `s` must be a valid pointer returned from a Rust FFI function
 * * Must only be called once per string
 */
void sequins_string_free(char *s);

/**
 * Generate test data for local data source
 *
 * # Arguments
 * * `data_source` - Local data source
 * * `error_out` - Output parameter for error message (if any)
 *
 * # Returns
 * * Number of spans created on success, 0 on failure
 * * On failure, `error_out` contains error message
 *
 * # Safety
 * * `data_source` must be a valid local DataSource
 * * Only works with local DataSource (returns error for remote)
 */
uintptr_t sequins_data_source_generate_test_data(struct CDataSource *data_source, char **error_out);

/**
 * Update retention policy for data source
 *
 * # Arguments
 * * `data_source` - DataSource to configure
 * * `policy` - New retention policy
 * * `error_out` - Output parameter for error message (if any)
 *
 * # Returns
 * * true on success, false on error
 * * On error, `error_out` contains error message (caller must free with `sequins_string_free`)
 *
 * # Safety
 * * `data_source` must be a valid DataSource pointer
 */
bool sequins_management_update_retention_policy(struct CDataSource *data_source,
                                                struct CRetentionPolicy policy,
                                                char **error_out);

/**
 * Get current retention policy
 *
 * # Arguments
 * * `data_source` - DataSource to query
 * * `policy_out` - Output parameter for retention policy
 * * `error_out` - Output parameter for error message (if any)
 *
 * # Returns
 * * true on success, false on error
 * * On success, `policy_out` contains the current policy
 * * On error, `error_out` contains error message (caller must free with `sequins_string_free`)
 *
 * # Safety
 * * `data_source` must be a valid DataSource pointer
 * * `policy_out` must be a valid pointer
 */
bool sequins_management_get_retention_policy(struct CDataSource *data_source,
                                             struct CRetentionPolicy *policy_out,
                                             char **error_out);

/**
 * Get storage statistics
 *
 * # Arguments
 * * `data_source` - DataSource to query
 * * `stats_out` - Output parameter for storage stats
 * * `error_out` - Output parameter for error message (if any)
 *
 * # Returns
 * * true on success, false on error
 * * On success, `stats_out` contains current statistics
 * * On error, `error_out` contains error message (caller must free with `sequins_string_free`)
 *
 * # Safety
 * * `data_source` must be a valid DataSource pointer
 * * `stats_out` must be a valid pointer
 */
bool sequins_management_get_storage_stats(struct CDataSource *data_source,
                                          struct CStorageStats *stats_out,
                                          char **error_out);

/**
 * Run retention cleanup to delete old data
 *
 * # Arguments
 * * `data_source` - DataSource to clean up
 * * `deleted_count_out` - Output parameter for number of deleted entries
 * * `error_out` - Output parameter for error message (if any)
 *
 * # Returns
 * * true on success, false on error
 * * On success, `deleted_count_out` contains number of entries deleted
 * * On error, `error_out` contains error message (caller must free with `sequins_string_free`)
 *
 * # Safety
 * * `data_source` must be a valid DataSource pointer
 * * `deleted_count_out` must be a valid pointer
 */
bool sequins_management_run_retention_cleanup(struct CDataSource *data_source,
                                              uintptr_t *deleted_count_out,
                                              char **error_out);

/**
 * Run database maintenance (compaction and optimization)
 *
 * # Arguments
 * * `data_source` - DataSource to maintain
 * * `stats_out` - Output parameter for maintenance statistics
 * * `error_out` - Output parameter for error message (if any)
 *
 * # Returns
 * * true on success, false on error
 * * On success, `stats_out` contains maintenance statistics
 * * On error, `error_out` contains error message (caller must free with `sequins_string_free`)
 *
 * # Safety
 * * `data_source` must be a valid DataSource pointer
 * * `stats_out` must be a valid pointer
 */
bool sequins_management_run_maintenance(struct CDataSource *data_source,
                                        struct CMaintenanceStats *stats_out,
                                        char **error_out);

/**
 * Get current health threshold configuration
 *
 * # Arguments
 * * `data_source` - DataSource to query
 * * `config_out` - Output parameter for health config
 * * `error_out` - Output parameter for error message (if any)
 *
 * # Returns
 * * true on success, false on error
 * * On success, `config_out` contains the current config
 * * On error, `error_out` contains error message (caller must free with `sequins_string_free`)
 *
 * # Safety
 * * `data_source` must be a valid DataSource pointer
 * * `config_out` must be a valid pointer
 * * Caller must free the returned config with `sequins_health_threshold_config_free`
 */
bool sequins_management_get_health_threshold_config(struct CDataSource *data_source,
                                                    struct CHealthThresholdConfig *config_out,
                                                    char **error_out);

/**
 * Set health threshold configuration
 *
 * # Arguments
 * * `data_source` - DataSource to configure
 * * `config` - New health threshold config
 * * `error_out` - Output parameter for error message (if any)
 *
 * # Returns
 * * true on success, false on error
 * * On error, `error_out` contains error message (caller must free with `sequins_string_free`)
 *
 * # Safety
 * * `data_source` must be a valid DataSource pointer
 * * `config` must be a valid pointer to a CHealthThresholdConfig
 */
bool sequins_management_set_health_threshold_config(struct CDataSource *data_source,
                                                    const struct CHealthThresholdConfig *config,
                                                    char **error_out);

/**
 * Add a health metric rule
 *
 * If a rule with the same metric_name and service_name already exists, it is replaced.
 *
 * # Arguments
 * * `data_source` - DataSource to configure
 * * `rule` - Health metric rule to add
 * * `error_out` - Output parameter for error message (if any)
 *
 * # Returns
 * * true on success, false on error
 * * On error, `error_out` contains error message (caller must free with `sequins_string_free`)
 *
 * # Safety
 * * `data_source` must be a valid DataSource pointer
 * * `rule` must be a valid pointer to a CHealthMetricRule
 */
bool sequins_management_add_health_rule(struct CDataSource *data_source,
                                        const struct CHealthMetricRule *rule,
                                        char **error_out);

/**
 * Remove a health metric rule
 *
 * # Arguments
 * * `data_source` - DataSource to configure
 * * `metric_name` - Metric name of the rule to remove
 * * `service_name` - Service name filter (null = all services)
 * * `error_out` - Output parameter for error message (if any)
 *
 * # Returns
 * * true on success, false on error
 * * On error, `error_out` contains error message (caller must free with `sequins_string_free`)
 *
 * # Safety
 * * `data_source` must be a valid DataSource pointer
 * * `metric_name` must be a valid C string
 * * `service_name` can be null (means all services)
 */
bool sequins_management_remove_health_rule(struct CDataSource *data_source,
                                           const char *metric_name,
                                           const char *service_name,
                                           char **error_out);

/**
 * Parse a SeQL query text
 *
 * Returns an opaque `CParseResult*`. The caller must free it with
 * `sequins_seql_parse_result_free`.
 *
 * Check `sequins_seql_parse_result_is_ok` to determine success.
 *
 * # Safety
 * `query_text` must be a valid null-terminated UTF-8 string.
 */
struct CParseResult *sequins_seql_parse(const char *query_text);

/**
 * Returns 1 if the parse succeeded, 0 if there was a parse error
 *
 * # Safety
 * `result` must be a valid `CParseResult*` from `sequins_seql_parse`.
 */
int sequins_seql_parse_result_is_ok(const struct CParseResult *result);

/**
 * Returns the parse error message, or NULL if the parse succeeded.
 * The returned pointer is valid until `sequins_seql_parse_result_free` is called.
 *
 * # Safety
 * `result` must be a valid `CParseResult*` from `sequins_seql_parse`.
 */
const char *sequins_seql_parse_error_message(const struct CParseResult *result);

/**
 * Returns the byte offset of the parse error, or 0 on success.
 *
 * # Safety
 * `result` must be a valid `CParseResult*` from `sequins_seql_parse`.
 */
uintptr_t sequins_seql_parse_error_offset(const struct CParseResult *result);

/**
 * Free a `CParseResult` returned by `sequins_seql_parse`
 *
 * # Safety
 * `result` must be a valid `CParseResult*` from `sequins_seql_parse`.
 */
void sequins_seql_parse_result_free(struct CParseResult *result);

/**
 * Cancel a running SeQL stream
 *
 * This is a best-effort cancellation. The stream may produce a few more frames
 * before actually stopping. The `CStreamHandle` should still be freed with
 * `sequins_seql_stream_free`.
 *
 * # Safety
 * `handle` must be a valid `CStreamHandle*` from `sequins_seql_query`.
 */
void sequins_seql_cancel(struct CStreamHandle *handle);

/**
 * Execute a SeQL query (compile + execute in one call)
 *
 * This is the primary FFI entry point for executing SeQL queries.
 * It compiles and executes the query in a single call, returning a stream handle.
 *
 * # Parameters
 * - `data_source`: Pointer to the C data source (created via `sequins_create_data_source`)
 * - `query_text`: Null-terminated SeQL query string
 * - `vtable`: Callback vtable for receiving frames
 * - `ctx`: User context pointer passed to callbacks
 *
 * # Safety
 * - `data_source` must be a valid `CDataSource*` for the duration of the stream
 * - `query_text` must be a valid null-terminated UTF-8 string
 * - `vtable` function pointers must remain valid until the stream completes
 * - `ctx` must be valid for the duration of the stream
 */
struct CStreamHandle *sequins_seql_query(struct CDataSource *data_source,
                                         const char *query_text,
                                         struct CFrameSinkVTable vtable,
                                         void *ctx);

/**
 * Execute a SeQL query in live streaming mode
 *
 * Identical to `sequins_seql_query` except the query runs in live mode:
 * - The backend subscribes to the WAL broadcast channel for new data
 * - The stream emits Delta frames as new rows arrive
 * - The stream emits Heartbeat frames as keepalives
 * - The stream never emits a Complete frame — it runs until cancelled
 *
 * # Parameters
 * Same as `sequins_seql_query`.
 *
 * # Safety
 * Same as `sequins_seql_query`.
 */
struct CStreamHandle *sequins_seql_query_live(struct CDataSource *data_source,
                                              const char *query_text,
                                              struct CFrameSinkVTable vtable,
                                              void *ctx);

/**
 * Free a `CStreamHandle` returned by `sequins_seql_query`
 *
 * Call this after the stream has completed or been cancelled.
 *
 * **CRITICAL**: This function aborts the task and blocks until it completes
 * to prevent callbacks from firing after the Swift context is freed.
 *
 * # Safety
 * `handle` must be a valid `CStreamHandle*` from `sequins_seql_query`.
 */
void sequins_seql_stream_free(struct CStreamHandle *handle);

/**
 * Create a reactive view that transforms a live SeQL query into entity-level
 * deltas delivered to `on_deltas`.
 *
 * # Parameters
 * - `data_source`   — local data source (remote not yet supported)
 * - `query`         — SeQL query text
 * - `strategy`      — [`CViewStrategy`] variant
 * - `retention_ns`  — retention window in nanoseconds; if 0, defaults to 1 hour.
 *   Only meaningful for `Flamegraph` strategy.
 * - `on_deltas`     — callback invoked with a heap-allocated batch of deltas.
 *   Caller must free with `c_view_delta_batch_free`.
 * - `ctx`           — user context pointer forwarded to `on_deltas`
 *
 * Returns a [`CViewHandle*`] that must be freed with `sequins_view_free`.
 * Returns NULL on invalid input.
 *
 * # Safety
 * - `data_source` must be a valid `CDataSource*` for the duration of the handle
 * - `query` must be a valid null-terminated UTF-8 string
 * - `on_deltas` must be a valid function pointer for the duration of the handle
 * - `ctx` must be valid for the duration of the handle
 */
struct CViewHandle *sequins_view_create(struct CDataSource *data_source,
                                        const char *query,
                                        uint32_t strategy,
                                        uint64_t retention_ns,
                                        void (*on_deltas)(struct CViewDelta*, uint32_t, void*),
                                        void *ctx);

/**
 * Cancel a running view (best-effort).
 *
 * The handle must still be freed with `sequins_view_free`.
 *
 * # Safety
 * `handle` must be a valid `CViewHandle*` from `sequins_view_create`.
 */
void sequins_view_cancel(struct CViewHandle *handle);

/**
 * Free a `CViewHandle` returned by `sequins_view_create`.
 *
 * Aborts the background task and blocks until it stops to prevent callbacks
 * firing after the Swift context is freed.
 *
 * # Safety
 * `handle` must be a valid `CViewHandle*` from `sequins_view_create`.
 */
void sequins_view_free(struct CViewHandle *handle);

/**
 * Free a CAttributeValue and its contents
 */
void sequins_attribute_value_free(struct CAttributeValue value);

/**
 * Free a CKeyValueArray and all its contents
 */
void sequins_key_value_array_free(struct CKeyValueArray arr);

/**
 * Free a CQueryCursor
 */
void sequins_cursor_free(struct CQueryCursor cursor);

/**
 * Free a `CSchemaFrame` allocated by Rust
 *
 * # Safety
 * Pointer must be a valid `CSchemaFrame` created by `sequins_seql_*` functions.
 */
void c_schema_frame_free(struct CSchemaFrame *frame);

/**
 * Free a `CDataFrame` allocated by Rust
 *
 * # Safety
 * Pointer must be a valid `CDataFrame` created by `sequins_seql_*` functions.
 */
void c_data_frame_free(struct CDataFrame *frame);

/**
 * Free a `CWarningFrame` allocated by Rust
 *
 * # Safety
 * Pointer must be a valid `CWarningFrame` created by `sequins_seql_*` functions.
 */
void c_warning_frame_free(struct CWarningFrame *frame);

/**
 * Free a `CQueryError` allocated by Rust
 *
 * # Safety
 * Pointer must be a valid `CQueryError` created by `sequins_seql_*` functions.
 */
void c_query_error_free(struct CQueryError *err);

/**
 * Free a `CDeltaFrame` allocated by Rust
 *
 * # Safety
 * Pointer must be a valid `CDeltaFrame` created by `sequins_seql_*` functions.
 */
void c_delta_frame_free(struct CDeltaFrame *frame);

/**
 * Free a `CHeartbeatFrame` allocated by Rust
 *
 * # Safety
 * Pointer must be a valid `CHeartbeatFrame` created by `sequins_seql_*` functions.
 * Note: Currently a no-op since CHeartbeatFrame contains no heap allocations,
 * but provided for API consistency.
 */
void c_heartbeat_frame_free(struct CHeartbeatFrame *_frame);

/**
 * Free a CHealthMetricRule and its contents
 */
void sequins_health_metric_rule_free(struct CHealthMetricRule rule);

/**
 * Free a CHealthMetricRuleArray and all its contents
 */
void sequins_health_metric_rule_array_free(struct CHealthMetricRuleArray arr);

/**
 * Free a CHealthThresholdConfig and all its contents
 */
void sequins_health_threshold_config_free(struct CHealthThresholdConfig config);

/**
 * Stub function to ensure CLogQuery is exported to C header
 */
struct CLogQueryResult sequins_query_logs_stub(struct CLogQuery _query);

/**
 * Free a CLogEntry and all its contents
 *
 * # Safety
 * * Must only be called once per CLogEntry
 * * All pointers must be valid
 */
void sequins_log_entry_free(struct CLogEntry log);

/**
 * Free a CLogEntryArray and all its contents
 */
void sequins_log_entry_array_free(struct CLogEntryArray arr);

/**
 * Free a CLogQueryResult and all its contents
 */
void sequins_log_query_result_free(struct CLogQueryResult result);

/**
 * Stub function to ensure CMetricDataPointQuery is exported to C header
 */
struct CMetricDataPointQueryResult sequins_query_metric_data_points_stub(struct CMetricDataPointQuery _query);

/**
 * Stub function to ensure CMetricQuery is exported to C header
 */
struct CMetricQueryResult sequins_query_metrics_stub(struct CMetricQuery _query);

/**
 * Free a CMetric and its contents
 *
 * # Safety
 * * Must only be called once per CMetric
 * * All pointers must be valid
 */
void sequins_metric_free(struct CMetric metric);

/**
 * Free a CMetricDataPoint and its contents
 *
 * # Safety
 * * Must only be called once per CMetricDataPoint
 * * All pointers must be valid
 */
void sequins_metric_data_point_free(struct CMetricDataPoint point);

/**
 * Free a CMetricArray and all its contents
 */
void sequins_metric_array_free(struct CMetricArray arr);

/**
 * Free a CMetricQueryResult and all its contents
 */
void sequins_metric_query_result_free(struct CMetricQueryResult result);

/**
 * Free a CMetricDataPointArray and all its contents
 */
void sequins_metric_data_point_array_free(struct CMetricDataPointArray arr);

/**
 * Free a CMetricDataPointQueryResult and all its contents
 */
void sequins_metric_data_point_query_result_free(struct CMetricDataPointQueryResult result);

/**
 * Free a CMetricGroup and its contents
 *
 * # Safety
 * * Must only be called once per CMetricGroup
 * * All pointers must be valid
 */
void sequins_metric_group_free(struct CMetricGroup group);

/**
 * Free a CMetricGroupArray and all its contents
 */
void sequins_metric_group_array_free(struct CMetricGroupArray arr);

/**
 * Stub function to ensure CProfileSampleQuery is exported to C header
 */
struct CProfileSampleQueryResult sequins_query_profile_samples_stub(struct CProfileSampleQuery _query);

/**
 * Free a CProfileSample and its contents
 *
 * # Safety
 * * Must only be called once per CProfileSample
 * * All pointers must be valid
 */
void sequins_profile_sample_free(struct CProfileSample sample);

/**
 * Free a CProfileSampleArray and all its contents
 */
void sequins_profile_sample_array_free(struct CProfileSampleArray arr);

/**
 * Free a CProfileSampleQueryResult and all its contents
 */
void sequins_profile_sample_query_result_free(struct CProfileSampleQueryResult result);

/**
 * Free a CByteArray
 *
 * # Safety
 * * Must only be called once per CByteArray
 * * All pointers must be valid
 */
void sequins_byte_array_free(struct CByteArray arr);

/**
 * Stub function to ensure CProfileQuery is exported to C header
 *
 * This function is not implemented - use SeQL queries instead
 */
struct CProfileQueryResult sequins_query_profiles_stub(struct CProfileQuery _query);

/**
 * Free a CProfile and its contents
 *
 * # Safety
 * * Must only be called once per CProfile
 * * All pointers must be valid
 */
void sequins_profile_free(struct CProfile profile);

/**
 * Free a CProfileArray and all its contents
 */
void sequins_profile_array_free(struct CProfileArray arr);

/**
 * Free a CProfileQueryResult and all its contents
 */
void sequins_profile_query_result_free(struct CProfileQueryResult result);

/**
 * Free a CResourceAttribute and its contents
 *
 * # Safety
 * * Must only be called once per CResourceAttribute
 * * All pointers must be valid
 */
void sequins_resource_attribute_free(struct CResourceAttribute attr);

/**
 * Free a CResourceAttributeArray and all its contents
 *
 * # Safety
 * * Must only be called once per CResourceAttributeArray
 * * All pointers must be valid
 */
void sequins_resource_attribute_array_free(struct CResourceAttributeArray arr);

/**
 * Free a CService and its contents
 *
 * # Safety
 * * Must only be called once per CService
 * * All pointers must be valid
 */
void sequins_service_free(struct CService service);

/**
 * Free a CServiceArray and all its contents
 *
 * # Safety
 * * Must only be called once per CServiceArray
 * * All pointers must be valid
 */
void sequins_service_array_free(struct CServiceArray arr);

/**
 * Stub function to ensure CSpanQuery is exported to C header
 */
struct CSpanQueryResult sequins_query_spans_stub(struct CSpanQuery _query);

/**
 * Free a CSpan and all its contents
 *
 * # Safety
 * * Must only be called once per CSpan
 * * All pointers must be valid
 */
void sequins_span_free(struct CSpan span);

/**
 * Free a CSpanArray and all its contents
 */
void sequins_span_array_free(struct CSpanArray arr);

/**
 * Free a CSpanQueryResult and all its contents
 */
void sequins_span_query_result_free(struct CSpanQueryResult result);

/**
 * Free a batch of [`CViewDelta`]s allocated by `sequins_view_create`.
 *
 * # Safety
 * `deltas` must be a pointer returned by the `on_deltas` callback, and
 * `count` must match the value passed to that callback. Must only be called
 * once per batch.
 */
void c_view_delta_batch_free(struct CViewDelta *deltas, uint32_t count);

#endif /* SEQUINS_FFI_H */
