import Foundation
import SwiftUI

// MARK: - Health Metric Names

/// Constants for health metric names generated by the Rust backend
public enum HealthMetricNames {
    /// Span error rate (0.0-1.0)
    public static let spanErrorRate = "sequins.health.span_error_rate"
    /// HTTP error rate from status codes (0.0-1.0)
    public static let httpErrorRate = "sequins.health.http_error_rate"
    /// Latency p50 percentile (nanoseconds)
    public static let latencyP50 = "sequins.health.latency_p50"
    /// Latency p95 percentile (nanoseconds)
    public static let latencyP95 = "sequins.health.latency_p95"
    /// Latency p99 percentile (nanoseconds)
    public static let latencyP99 = "sequins.health.latency_p99"
    /// Throughput (spans per minute)
    public static let throughput = "sequins.health.throughput"
    /// Error log rate (logs per minute)
    public static let errorLogRate = "sequins.health.error_log_rate"

    /// All health metric names
    public static let all: [String] = [
        spanErrorRate,
        httpErrorRate,
        latencyP50,
        latencyP95,
        latencyP99,
        throughput,
        errorLogRate
    ]
}

// MARK: - Health Status

/// Overall health status of a service
public enum HealthStatus: String, CaseIterable, Sendable {
    case healthy
    case degraded
    case unhealthy
    case inactive

    /// Display color for this status
    public var color: Color {
        switch self {
        case .healthy:
            return .green
        case .degraded:
            return .yellow
        case .unhealthy:
            return .red
        case .inactive:
            return .gray
        }
    }

    /// Human-readable label
    public var label: String {
        switch self {
        case .healthy:
            return "Healthy"
        case .degraded:
            return "Degraded"
        case .unhealthy:
            return "Unhealthy"
        case .inactive:
            return "Inactive"
        }
    }

    /// Icon name for this status
    public var iconName: String {
        switch self {
        case .healthy:
            return "checkmark.circle.fill"
        case .degraded:
            return "exclamationmark.triangle.fill"
        case .unhealthy:
            return "xmark.circle.fill"
        case .inactive:
            return "circle.fill"
        }
    }
}

// MARK: - Health Thresholds

/// User-configurable thresholds for determining health status
public struct HealthThresholds: Codable, Sendable {
    // Error rate thresholds (0.0-1.0)
    /// Below this = healthy
    public var errorRateHealthy: Double
    /// Below this = degraded, above = unhealthy
    public var errorRateDegraded: Double

    // HTTP error thresholds (0.0-1.0)
    public var httpErrorRateHealthy: Double
    public var httpErrorRateDegraded: Double

    // Latency thresholds (milliseconds)
    public var latencyP95HealthyMs: Double
    public var latencyP95DegradedMs: Double

    // Error log thresholds (per minute)
    public var errorLogsPerMinHealthy: Double
    public var errorLogsPerMinDegraded: Double

    public init(
        errorRateHealthy: Double = 0.01,
        errorRateDegraded: Double = 0.05,
        httpErrorRateHealthy: Double = 0.05,
        httpErrorRateDegraded: Double = 0.15,
        latencyP95HealthyMs: Double = 200.0,
        latencyP95DegradedMs: Double = 500.0,
        errorLogsPerMinHealthy: Double = 5.0,
        errorLogsPerMinDegraded: Double = 20.0
    ) {
        self.errorRateHealthy = errorRateHealthy
        self.errorRateDegraded = errorRateDegraded
        self.httpErrorRateHealthy = httpErrorRateHealthy
        self.httpErrorRateDegraded = httpErrorRateDegraded
        self.latencyP95HealthyMs = latencyP95HealthyMs
        self.latencyP95DegradedMs = latencyP95DegradedMs
        self.errorLogsPerMinHealthy = errorLogsPerMinHealthy
        self.errorLogsPerMinDegraded = errorLogsPerMinDegraded
    }

    /// Default thresholds
    public static let `default` = HealthThresholds()
}

// MARK: - Health Weights

/// User-configurable weights for computing overall health score
public struct HealthWeights: Codable, Sendable {
    public var spanErrorRate: Double
    public var httpErrorRate: Double
    public var latency: Double
    public var errorLogs: Double

    public init(
        spanErrorRate: Double = 0.40,
        httpErrorRate: Double = 0.25,
        latency: Double = 0.20,
        errorLogs: Double = 0.15
    ) {
        self.spanErrorRate = spanErrorRate
        self.httpErrorRate = httpErrorRate
        self.latency = latency
        self.errorLogs = errorLogs
    }

    /// Normalized weights (sum to 1.0)
    public var normalized: HealthWeights {
        let total = spanErrorRate + httpErrorRate + latency + errorLogs
        guard total > 0 else { return self }
        return HealthWeights(
            spanErrorRate: spanErrorRate / total,
            httpErrorRate: httpErrorRate / total,
            latency: latency / total,
            errorLogs: errorLogs / total
        )
    }

    /// Default weights
    public static let `default` = HealthWeights()
}

// MARK: - Health Metric Rule (Configurable)

/// A rule defining how a metric contributes to health status
///
/// Each rule specifies warning and error thresholds for a metric,
/// as well as the weight it contributes to the overall health score.
public struct HealthMetricRule: Codable, Sendable, Identifiable, Equatable {
    /// Unique identifier based on metric name and service
    public var id: String { metricName + (serviceName ?? "") }

    /// Metric name (exact match, e.g., "sequins.health.span_error_rate" or "my.custom.metric")
    public var metricName: String

    /// Service name filter (nil = applies to all services)
    public var serviceName: String?

    /// Warning threshold - above this value = degraded/warning status
    public var warningThreshold: Double

    /// Error threshold - above this value = unhealthy/error status
    public var errorThreshold: Double

    /// Whether higher values are worse (true) or lower values are worse (false)
    public var higherIsWorse: Bool

    /// Weight for overall health score (0.0-1.0, will be normalized)
    public var weight: Double

    /// Human-readable display name
    public var displayName: String

    public init(
        metricName: String,
        serviceName: String? = nil,
        warningThreshold: Double,
        errorThreshold: Double,
        higherIsWorse: Bool = true,
        weight: Double = 1.0,
        displayName: String
    ) {
        self.metricName = metricName
        self.serviceName = serviceName
        self.warningThreshold = warningThreshold
        self.errorThreshold = errorThreshold
        self.higherIsWorse = higherIsWorse
        self.weight = weight
        self.displayName = displayName
    }
}

// MARK: - Health Threshold Config

/// Configuration for health threshold rules
///
/// This defines which metrics contribute to health and their thresholds.
/// Stored in the Rust backend and can be shared across team members.
public struct HealthThresholdConfig: Codable, Sendable, Equatable {
    /// List of metric rules that define health
    public var rules: [HealthMetricRule]

    public init(rules: [HealthMetricRule] = HealthThresholdConfig.defaultRules) {
        self.rules = rules
    }

    /// Default health rules
    public static let defaultRules: [HealthMetricRule] = [
        HealthMetricRule(
            metricName: HealthMetricNames.spanErrorRate,
            warningThreshold: 0.01,  // 1%
            errorThreshold: 0.05,    // 5%
            weight: 0.40,
            displayName: "Span Error Rate"
        ),
        HealthMetricRule(
            metricName: HealthMetricNames.httpErrorRate,
            warningThreshold: 0.05,  // 5%
            errorThreshold: 0.15,    // 15%
            weight: 0.25,
            displayName: "HTTP Error Rate"
        ),
        HealthMetricRule(
            metricName: HealthMetricNames.latencyP95,
            warningThreshold: 200_000_000,  // 200ms in ns
            errorThreshold: 500_000_000,    // 500ms in ns
            weight: 0.20,
            displayName: "Latency (P95)"
        ),
        HealthMetricRule(
            metricName: HealthMetricNames.errorLogRate,
            warningThreshold: 5.0,   // 5/min
            errorThreshold: 20.0,    // 20/min
            weight: 0.15,
            displayName: "Error Log Rate"
        )
    ]

    /// Default configuration
    public static let `default` = HealthThresholdConfig()
}

// MARK: - Health Factor

/// Individual health factor evaluation
public struct HealthFactor: Identifiable, Sendable {
    public var id: String { metricName }

    /// Metric name (e.g., "sequins.health.span_error_rate")
    public let metricName: String

    /// Human-readable display name (e.g., "Span Error Rate")
    public let displayName: String

    /// The actual metric value (nil if data is missing)
    public let rawValue: Double?

    /// Formatted value for display
    public let formattedValue: String

    /// Score from 0.0 (bad) to 1.0 (good) based on thresholds
    public let score: Double

    /// Health status for this individual factor
    public let status: HealthStatus

    /// Weight of this factor in overall health
    public let weight: Double

    /// Whether this factor has data available
    public var hasData: Bool { rawValue != nil }

    public init(
        metricName: String,
        displayName: String,
        rawValue: Double?,
        formattedValue: String,
        score: Double,
        status: HealthStatus,
        weight: Double
    ) {
        self.metricName = metricName
        self.displayName = displayName
        self.rawValue = rawValue
        self.formattedValue = formattedValue
        self.score = score
        self.status = status
        self.weight = weight
    }

    /// Create a factor representing missing data
    public static func missing(
        metricName: String,
        displayName: String,
        weight: Double
    ) -> HealthFactor {
        HealthFactor(
            metricName: metricName,
            displayName: displayName,
            rawValue: nil,
            formattedValue: "No data",
            score: 0.0,
            status: .inactive,
            weight: weight
        )
    }
}

// MARK: - Health Analysis

/// Complete health analysis for a service
public struct HealthAnalysis: Sendable {
    /// Overall health status
    public let status: HealthStatus

    /// Individual factor evaluations (includes both available and missing metrics)
    public let factors: [HealthFactor]

    /// Overall health score (0.0 = bad, 1.0 = good)
    public let overallScore: Double

    /// When this analysis was computed
    public let timestamp: Date

    /// Service name this analysis is for
    public let serviceName: String

    /// Factors that have data available
    public var availableFactors: [HealthFactor] {
        factors.filter { $0.hasData }
    }

    /// Factors that are missing data
    public var missingFactors: [HealthFactor] {
        factors.filter { !$0.hasData }
    }

    /// Whether all configured metrics have data
    public var hasCompleteData: Bool {
        missingFactors.isEmpty
    }

    /// Whether any data is available at all
    public var hasAnyData: Bool {
        !availableFactors.isEmpty
    }

    /// Number of metrics with data vs total configured
    public var dataAvailability: (available: Int, total: Int) {
        (availableFactors.count, factors.count)
    }

    public init(
        status: HealthStatus,
        factors: [HealthFactor],
        overallScore: Double,
        timestamp: Date,
        serviceName: String
    ) {
        self.status = status
        self.factors = factors
        self.overallScore = overallScore
        self.timestamp = timestamp
        self.serviceName = serviceName
    }

    /// Create an inactive analysis (no data)
    public static func inactive(serviceName: String) -> HealthAnalysis {
        HealthAnalysis(
            status: .inactive,
            factors: [],
            overallScore: 0.0,
            timestamp: Date(),
            serviceName: serviceName
        )
    }
}

// MARK: - Health Analyzer

/// Analyzes health metrics and applies thresholds to compute health status
///
/// The analyzer uses a rule-based configuration where each rule specifies:
/// - A metric name to evaluate
/// - Warning and error thresholds
/// - Whether higher values are worse (true) or lower values are worse (false)
/// - A weight for the overall health score
///
/// The overall health status is determined by the worst individual status:
/// - Any metric at error level → overall = unhealthy
/// - Any metric at warning level (none at error) → overall = degraded
/// - All metrics below warning → overall = healthy
public struct HealthAnalyzer: Sendable {
    public let config: HealthThresholdConfig

    /// Normalized weights for the rules (sum to 1.0)
    private var normalizedWeights: [String: Double] {
        let totalWeight = config.rules.reduce(0.0) { $0 + $1.weight }
        guard totalWeight > 0 else { return [:] }
        var weights: [String: Double] = [:]
        for rule in config.rules {
            weights[rule.id] = rule.weight / totalWeight
        }
        return weights
    }

    public init(config: HealthThresholdConfig = .default) {
        self.config = config
    }

    /// Legacy initializer for backwards compatibility
    @available(*, deprecated, message: "Use init(config:) instead")
    public init(
        thresholds: HealthThresholds,
        weights: HealthWeights
    ) {
        // Convert legacy thresholds/weights to config
        let normalizedWeights = weights.normalized
        self.config = HealthThresholdConfig(rules: [
            HealthMetricRule(
                metricName: HealthMetricNames.spanErrorRate,
                warningThreshold: thresholds.errorRateHealthy,
                errorThreshold: thresholds.errorRateDegraded,
                higherIsWorse: true,
                weight: normalizedWeights.spanErrorRate,
                displayName: "Span Error Rate"
            ),
            HealthMetricRule(
                metricName: HealthMetricNames.httpErrorRate,
                warningThreshold: thresholds.httpErrorRateHealthy,
                errorThreshold: thresholds.httpErrorRateDegraded,
                higherIsWorse: true,
                weight: normalizedWeights.httpErrorRate,
                displayName: "HTTP Error Rate"
            ),
            HealthMetricRule(
                metricName: HealthMetricNames.latencyP95,
                warningThreshold: thresholds.latencyP95HealthyMs * 1_000_000,  // Convert ms to ns
                errorThreshold: thresholds.latencyP95DegradedMs * 1_000_000,
                higherIsWorse: true,
                weight: normalizedWeights.latency,
                displayName: "Latency (P95)"
            ),
            HealthMetricRule(
                metricName: HealthMetricNames.errorLogRate,
                warningThreshold: thresholds.errorLogsPerMinHealthy,
                errorThreshold: thresholds.errorLogsPerMinDegraded,
                higherIsWorse: true,
                weight: normalizedWeights.errorLogs,
                displayName: "Error Log Rate"
            )
        ])
    }

    /// Analyze health metrics for a service
    /// - Parameters:
    ///   - metrics: Dictionary of metric name to latest value
    ///   - serviceName: Name of the service
    /// - Returns: Complete health analysis
    public func analyze(
        metrics: [String: Double],
        serviceName: String
    ) -> HealthAnalysis {
        let weights = normalizedWeights
        var factors: [HealthFactor] = []
        var weightedScoreSum: Double = 0.0
        var totalWeight: Double = 0.0

        // Evaluate each rule - include both available and missing metrics
        for rule in config.rules {
            // Check if rule applies to this service
            if let ruleService = rule.serviceName, ruleService != serviceName {
                continue
            }

            let normalizedWeight = weights[rule.id] ?? rule.weight

            // Check if we have data for this metric
            if let value = metrics[rule.metricName] {
                // We have data - evaluate the metric
                let factor = evaluateMetric(value: value, rule: rule, weight: normalizedWeight)
                factors.append(factor)
                weightedScoreSum += factor.score * factor.weight
                totalWeight += factor.weight
            } else {
                // Missing data - add a placeholder factor
                let missingFactor = HealthFactor.missing(
                    metricName: rule.metricName,
                    displayName: rule.displayName,
                    weight: normalizedWeight
                )
                factors.append(missingFactor)
            }
        }

        // If no rules apply to this service, return inactive
        guard !factors.isEmpty else {
            return .inactive(serviceName: serviceName)
        }

        // Check if we have any data at all
        let availableFactors = factors.filter { $0.hasData }

        // Calculate overall score (only from available data)
        let overallScore = totalWeight > 0 ? weightedScoreSum / totalWeight : 0.0

        // Determine overall status based on worst factor WITH DATA
        // Missing data factors don't affect the status - only available metrics do
        // This ensures: any error → unhealthy, any warning → degraded
        let worstStatus: HealthStatus
        if availableFactors.isEmpty {
            // No data at all - inactive
            worstStatus = .inactive
        } else {
            worstStatus = availableFactors.map(\.status).max { lhs, rhs in
                statusSeverity(lhs) < statusSeverity(rhs)
            } ?? .inactive
        }

        return HealthAnalysis(
            status: worstStatus,
            factors: factors,
            overallScore: overallScore,
            timestamp: Date(),
            serviceName: serviceName
        )
    }

    // MARK: - Private Helpers

    /// Evaluate a single metric against a rule
    private func evaluateMetric(
        value: Double,
        rule: HealthMetricRule,
        weight: Double
    ) -> HealthFactor {
        let status: HealthStatus
        let score: Double

        if rule.higherIsWorse {
            // Higher values are worse (e.g., error rate, latency)
            if value <= rule.warningThreshold {
                status = .healthy
                // Score: 1.0 at 0, linearly decreasing to 0.7 at warning threshold
                score = rule.warningThreshold > 0
                    ? 1.0 - (value / rule.warningThreshold) * 0.3
                    : 1.0
            } else if value <= rule.errorThreshold {
                status = .degraded
                // Score: 0.7 at warning threshold, linearly decreasing to 0.3 at error threshold
                let range = rule.errorThreshold - rule.warningThreshold
                let position = range > 0 ? (value - rule.warningThreshold) / range : 1.0
                score = 0.7 - position * 0.4
            } else {
                status = .unhealthy
                // Score: 0.3 at error threshold, approaching 0 as value increases
                // Use exponential decay for smooth degradation
                let excess = value - rule.errorThreshold
                let decayRate = rule.errorThreshold > 0 ? rule.errorThreshold : 1.0
                score = max(0, 0.3 * exp(-excess / decayRate))
            }
        } else {
            // Lower values are worse (e.g., throughput, availability)
            if value >= rule.warningThreshold {
                status = .healthy
                score = 1.0
            } else if value >= rule.errorThreshold {
                status = .degraded
                let range = rule.warningThreshold - rule.errorThreshold
                let position = range > 0 ? (rule.warningThreshold - value) / range : 1.0
                score = 0.7 - position * 0.4
            } else {
                status = .unhealthy
                let excess = rule.errorThreshold - value
                let decayRate = rule.errorThreshold > 0 ? rule.errorThreshold : 1.0
                score = max(0, 0.3 * exp(-excess / decayRate))
            }
        }

        let formattedValue = formatMetricValue(value: value, metricName: rule.metricName)

        return HealthFactor(
            metricName: rule.metricName,
            displayName: rule.displayName,
            rawValue: value,
            formattedValue: formattedValue,
            score: score,
            status: status,
            weight: weight
        )
    }

    /// Format a metric value for display based on metric type
    private func formatMetricValue(value: Double, metricName: String) -> String {
        // Latency metrics are in nanoseconds, display as ms/s
        if metricName.contains("latency") {
            let valueMs = value / 1_000_000.0
            if valueMs < 1 {
                return String(format: "%.2fms", valueMs)
            } else if valueMs < 1000 {
                return String(format: "%.0fms", valueMs)
            } else {
                return String(format: "%.1fs", valueMs / 1000)
            }
        }

        // Rate metrics (0.0-1.0) display as percentage
        if metricName.contains("rate") && value <= 1.0 {
            return String(format: "%.1f%%", value * 100)
        }

        // Log rate displays as per-minute
        if metricName.contains("log") {
            return String(format: "%.1f/min", value)
        }

        // Throughput displays as per-minute
        if metricName.contains("throughput") {
            return String(format: "%.0f/min", value)
        }

        // Default formatting
        if value >= 1000 {
            return String(format: "%.1fK", value / 1000)
        } else if value >= 1 {
            return String(format: "%.1f", value)
        } else {
            return String(format: "%.3f", value)
        }
    }

    private func statusSeverity(_ status: HealthStatus) -> Int {
        switch status {
        case .healthy: return 0
        case .degraded: return 1
        case .unhealthy: return 2
        case .inactive: return 3
        }
    }
}
