crate::macros::define_uuid_id!(
    /// Internal log entry ID (generated by Sequins, not from OTLP)
    LogId
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_log_id_generation() {
        let id1 = LogId::new();
        let id2 = LogId::new();

        assert_ne!(id1, id2); // Should be unique
    }

    #[test]
    fn test_log_id_roundtrip() {
        use uuid::Uuid;
        let uuid = Uuid::new_v4();
        let id = LogId::from_uuid(uuid);
        assert_eq!(id.as_uuid(), uuid);
    }
}
