//! Macro for generating UUID-backed ID types used throughout Sequins.
//!
//! # Usage
//!
//! ```rust,ignore
//! define_uuid_id!(
//!     /// Internal log entry ID (generated by Sequins, not from OTLP)
//!     LogId
//! );
//! ```
//!
//! This expands to a `pub struct LogId(uuid::Uuid)` with:
//! - `new()` — random v4 UUID
//! - `from_uuid(uuid: Uuid) -> Self`
//! - `as_uuid(&self) -> Uuid`
//! - `to_hex(&self) -> String` — 32-char hex, no hyphens
//! - `from_hex(s: &str) -> Result<Self, String>` — accepts any UUID format
//! - `Default` (delegates to `new()`)
//! - `Serialize` / `Deserialize` (via serde)
//! - `Debug`, `Clone`, `Copy`, `PartialEq`, `Eq`, `Hash`

#[macro_export]
macro_rules! define_uuid_id {
    ($(#[$attr:meta])* $name:ident) => {
        $(#[$attr])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
        pub struct $name(uuid::Uuid);

        impl $name {
            /// Generate a new random ID.
            pub fn new() -> Self {
                Self(uuid::Uuid::new_v4())
            }

            /// Create from an existing UUID.
            pub fn from_uuid(uuid: uuid::Uuid) -> Self {
                Self(uuid)
            }

            /// Return the inner UUID.
            pub fn as_uuid(&self) -> uuid::Uuid {
                self.0
            }

            /// Convert to a 32-character lowercase hex string (no hyphens).
            pub fn to_hex(&self) -> String {
                self.0.simple().to_string()
            }

            /// Parse from a hex string (with or without hyphens).
            ///
            /// # Errors
            ///
            /// Returns an error string if the input is not a valid UUID.
            pub fn from_hex(s: &str) -> Result<Self, String> {
                uuid::Uuid::parse_str(s)
                    .map(Self::from_uuid)
                    .map_err(|e| format!("Invalid UUID: {}", e))
            }
        }

        impl Default for $name {
            fn default() -> Self {
                Self::new()
            }
        }
    };
}
